package extract

import (
	"bytes"
	"context"
	"encoding/binary"
	"fmt"
	"strings"
	"testing"
)

// Every fixture is BUILT IN CODE (the same discipline as extract_test.go): a
// hand-assembled STL is readable in the diff, cannot bit-rot, and keeps binary
// blobs out of the repository. All of them describe the SAME unit cube, so the
// per-format numbers can be compared against each other as well as against the
// expected values.

var cubeVerts = [8][3]float64{
	{0, 0, 0}, {1, 0, 0}, {1, 1, 0}, {0, 1, 0},
	{0, 0, 1}, {1, 0, 1}, {1, 1, 1}, {0, 1, 1},
}

// cubeQuads is the cube as six QUADS. Keeping the faces four-sided is what pins
// the n-2 fan rule: a correct parser reports 12 triangles from 6 faces.
var cubeQuads = [6][4]int{
	{0, 3, 2, 1}, {4, 5, 6, 7}, {0, 1, 5, 4}, {1, 2, 6, 5}, {2, 3, 7, 6}, {3, 0, 4, 7},
}

// cubeTris fan-triangulates the quads the way every parser here does.
func cubeTris() [][3]int {
	out := make([][3]int, 0, 12)
	for _, q := range cubeQuads {
		out = append(out, [3]int{q[0], q[1], q[2]}, [3]int{q[0], q[2], q[3]})
	}
	return out
}

func binarySTL(t *testing.T, tris [][3]int, header string) []byte {
	t.Helper()
	var b bytes.Buffer
	head := make([]byte, 80)
	copy(head, header)
	b.Write(head)
	must(t, binary.Write(&b, binary.LittleEndian, uint32(len(tris))))
	for _, tr := range tris {
		must(t, binary.Write(&b, binary.LittleEndian, [3]float32{0, 0, 1}))
		for _, vi := range tr {
			v := cubeVerts[vi]
			must(t, binary.Write(&b, binary.LittleEndian,
				[3]float32{float32(v[0]), float32(v[1]), float32(v[2])}))
		}
		b.Write([]byte{0, 0}) // attribute byte count
	}
	return b.Bytes()
}

func asciiSTL(tris [][3]int) []byte {
	var b strings.Builder
	b.WriteString("solid cube\n")
	for _, tr := range tris {
		b.WriteString("  facet normal 0 0 1\n    outer loop\n")
		for _, vi := range tr {
			v := cubeVerts[vi]
			fmt.Fprintf(&b, "      vertex %g %g %g\n", v[0], v[1], v[2])
		}
		b.WriteString("    endloop\n  endfacet\n")
	}
	b.WriteString("endsolid cube\n")
	return []byte(b.String())
}

func objCube() []byte {
	var b strings.Builder
	// A comment line far past bufio.Scanner's 64 KiB default token limit: real
	// exporters emit long banners, and a scanner left at the default would fail
	// this ordinary file.
	b.WriteString("# generated by a test " + strings.Repeat("x", 200_000) + "\n")
	for _, v := range cubeVerts {
		fmt.Fprintf(&b, "v %g %g %g\n", v[0], v[1], v[2])
	}
	b.WriteString("vt 0 0\nvt 1 0\nvn 0 0 1\n") // must NOT be counted as vertices
	for _, q := range cubeQuads {
		fmt.Fprintf(&b, "f %d/1/1 %d/2/1 %d/1/1 %d/2/1\n", q[0]+1, q[1]+1, q[2]+1, q[3]+1)
	}
	return []byte(b.String())
}

func plyCube() []byte {
	var b strings.Builder
	b.WriteString("ply\nformat ascii 1.0\ncomment built by a test\n")
	b.WriteString("element vertex 8\nproperty float x\nproperty float y\nproperty float z\n")
	b.WriteString("element face 6\nproperty list uchar int vertex_indices\nend_header\n")
	for _, v := range cubeVerts {
		fmt.Fprintf(&b, "%g %g %g\n", v[0], v[1], v[2])
	}
	for _, q := range cubeQuads {
		fmt.Fprintf(&b, "4 %d %d %d %d\n", q[0], q[1], q[2], q[3])
	}
	return []byte(b.String())
}

func offCube() []byte {
	var b strings.Builder
	b.WriteString("OFF\n# a comment in the middle of the header\n8 6 0\n")
	for _, v := range cubeVerts {
		fmt.Fprintf(&b, "%g %g %g\n", v[0], v[1], v[2])
	}
	for _, q := range cubeQuads {
		fmt.Fprintf(&b, "4 %d %d %d %d\n", q[0], q[1], q[2], q[3])
	}
	return []byte(b.String())
}

// gltfCube is a minimal glTF 2.0 asset: one mesh, one indexed primitive, and the
// POSITION accessor's mandatory min/max (which is where the bbox comes from —
// no buffer is ever decoded).
const gltfCube = `{
  "asset": {"version": "2.0"},
  "meshes": [{"primitives": [{"attributes": {"POSITION": 0}, "indices": 1}]}],
  "accessors": [
    {"count": 8, "type": "VEC3", "min": [0, 0, 0], "max": [1, 1, 1]},
    {"count": 36, "type": "SCALAR"}
  ]
}`

func glbOf(t *testing.T, doc string) []byte {
	t.Helper()
	chunk := []byte(doc)
	for len(chunk)%4 != 0 {
		chunk = append(chunk, ' ') // GLB chunks are 4-byte aligned, padded with spaces
	}
	var b bytes.Buffer
	b.WriteString("glTF")
	must(t, binary.Write(&b, binary.LittleEndian, uint32(2)))
	must(t, binary.Write(&b, binary.LittleEndian, uint32(12+8+len(chunk))))
	must(t, binary.Write(&b, binary.LittleEndian, uint32(len(chunk))))
	must(t, binary.Write(&b, binary.LittleEndian, uint32(0x4E4F534A))) // 'JSON'
	b.Write(chunk)
	return b.Bytes()
}

func threeMFCube(t *testing.T) []byte {
	t.Helper()
	var b strings.Builder
	b.WriteString(`<?xml version="1.0" encoding="UTF-8"?>` + "\n")
	b.WriteString(`<model unit="millimeter" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02">`)
	b.WriteString(`<resources><object id="1" type="model"><mesh><vertices>`)
	for _, v := range cubeVerts {
		fmt.Fprintf(&b, `<vertex x="%g" y="%g" z="%g"/>`, v[0], v[1], v[2])
	}
	b.WriteString(`</vertices><triangles>`)
	for _, tr := range cubeTris() {
		fmt.Fprintf(&b, `<triangle v1="%d" v2="%d" v3="%d"/>`, tr[0], tr[1], tr[2])
	}
	b.WriteString(`</triangles></mesh></object></resources></model>`)
	return zipOf(t, [][2]string{
		{"[Content_Types].xml", `<Types/>`},
		{"3D/3dmodel.model", b.String()},
	})
}

func must(t *testing.T, err error) {
	t.Helper()
	if err != nil {
		t.Fatalf("fixture: %v", err)
	}
}

// runModel3D extracts one in-memory fixture and returns its metadata.
func runModel3D(t *testing.T, name string, data []byte) map[string]any {
	t.Helper()
	p := writeFile(t, t.TempDir(), name, data)
	res := &Result{Meta: map[string]any{}}
	if err := extractModel3D(context.Background(), p, lowerExt(p), Options{}, res); err != nil {
		t.Fatalf("extractModel3D(%s): %v", name, err)
	}
	return res.Meta
}

func runModel3DErr(t *testing.T, name string, data []byte) error {
	t.Helper()
	p := writeFile(t, t.TempDir(), name, data)
	res := &Result{Meta: map[string]any{}}
	return extractModel3D(context.Background(), p, lowerExt(p), Options{}, res)
}

// wantGeometry asserts the whole geometry vocabulary at once. bbox is the
// EXTENTS (max-min per axis), matching model3d.py's bounds[1]-bounds[0].
func wantGeometry(t *testing.T, m map[string]any, format string, tris, verts, meshes int, bbox [3]float64, vol float64) {
	t.Helper()
	wantKey(t, m, "triangles", tris)
	wantKey(t, m, "vertices", verts)
	wantKey(t, m, "mesh_count", meshes)
	wantKey(t, m, "file_format", format)
	got, ok := m["bbox"].([]float64)
	if !ok || len(got) != 3 {
		t.Fatalf("bbox = %#v, want a 3-element []float64", m["bbox"])
	}
	for i := range bbox {
		if got[i] != bbox[i] {
			t.Fatalf("bbox = %v, want %v", got, bbox)
		}
	}
	wantKey(t, m, "bbox_volume", vol)
}

func TestModel3DBinarySTL(t *testing.T) {
	// The 80-byte header deliberately starts with "solid": plenty of exporters
	// write that word into a BINARY file, which is why detection is the exact
	// 84+50n size arithmetic and not a magic-string sniff.
	m := runModel3D(t, "cube.stl", binarySTL(t, cubeTris(), "solid exported-by-a-binary-writer"))
	// vertices == 3*triangles: STL is a vertex soup and neither side merges it.
	wantGeometry(t, m, "stl", 12, 36, 1, [3]float64{1, 1, 1}, 1)
	wantKey(t, m, "watertight", true)
}

func TestModel3DASCIISTL(t *testing.T) {
	m := runModel3D(t, "cube.stl", asciiSTL(cubeTris()))
	wantGeometry(t, m, "stl", 12, 36, 1, [3]float64{1, 1, 1}, 1)
	wantKey(t, m, "watertight", true)
}

func TestModel3DSTLDialectsAgree(t *testing.T) {
	bin := runModel3D(t, "cube.stl", binarySTL(t, cubeTris(), "solid"))
	asc := runModel3D(t, "cube.stl", asciiSTL(cubeTris()))
	for _, k := range []string{"triangles", "vertices", "mesh_count", "bbox_volume", "watertight"} {
		if bin[k] != asc[k] {
			t.Fatalf("%s: binary %#v != ascii %#v", k, bin[k], asc[k])
		}
	}
}

func TestModel3DOBJ(t *testing.T) {
	// 6 quads -> 12 triangles (the n-2 fan rule), 8 vertices (vt/vn ignored).
	m := runModel3D(t, "cube.obj", objCube())
	wantGeometry(t, m, "obj", 12, 8, 1, [3]float64{1, 1, 1}, 1)
	wantKey(t, m, "watertight", true)
}

func TestModel3DOBJNegativeIndices(t *testing.T) {
	// A single quad addressed with OBJ's relative indices (-1 is the last vertex).
	obj := "v 0 0 0\nv 2 0 0\nv 2 3 0\nv 0 3 0\nf -4 -3 -2 -1\n"
	m := runModel3D(t, "quad.obj", []byte(obj))
	wantGeometry(t, m, "obj", 2, 4, 1, [3]float64{2, 3, 0}, 0)
}

func TestModel3DPLYASCII(t *testing.T) {
	m := runModel3D(t, "cube.ply", plyCube())
	wantGeometry(t, m, "ply", 12, 8, 1, [3]float64{1, 1, 1}, 1)
	wantKey(t, m, "watertight", true)
}

func TestModel3DOFF(t *testing.T) {
	m := runModel3D(t, "cube.off", offCube())
	wantGeometry(t, m, "off", 12, 8, 1, [3]float64{1, 1, 1}, 1)
	wantKey(t, m, "watertight", true)
}

func TestModel3DOFFRejectsUnknownVariant(t *testing.T) {
	// 4OFF's vertices are homogeneous 4-D coordinates; parsing them as x y z
	// would be silently wrong, so the variant is rejected explicitly.
	if err := runModel3DErr(t, "cube.off", []byte("4OFF\n1 0 0\n0 0 0 1\n")); err == nil {
		t.Fatal("expected 4OFF to be rejected")
	}
	if err := runModel3DErr(t, "cube.off", []byte("OFF BINARY\n")); err == nil {
		t.Fatal("expected binary OFF to be rejected")
	}
}

func TestModel3DGLTF(t *testing.T) {
	m := runModel3D(t, "cube.gltf", []byte(gltfCube))
	// triangles from the index accessor (36/3); bbox from the POSITION accessor's
	// mandatory min/max — no buffer is decoded.
	wantGeometry(t, m, "gltf", 12, 8, 1, [3]float64{1, 1, 1}, 1)
	wantAbsent(t, m, "watertight") // topology was never read, so it is not claimed
}

func TestModel3DGLB(t *testing.T) {
	m := runModel3D(t, "cube.glb", glbOf(t, gltfCube))
	wantGeometry(t, m, "glb", 12, 8, 1, [3]float64{1, 1, 1}, 1)
	wantAbsent(t, m, "watertight")
}

func TestModel3DGLTFUnindexedPrimitive(t *testing.T) {
	doc := `{"meshes":[{"primitives":[{"attributes":{"POSITION":0}}]}],
	         "accessors":[{"count":36,"min":[0,0,0],"max":[2,2,2]}]}`
	m := runModel3D(t, "soup.gltf", []byte(doc))
	// No index accessor: triangles fall back to POSITION count / 3.
	wantGeometry(t, m, "gltf", 12, 36, 1, [3]float64{2, 2, 2}, 8)
}

func TestModel3D3MF(t *testing.T) {
	m := runModel3D(t, "cube.3mf", threeMFCube(t))
	wantGeometry(t, m, "3mf", 12, 8, 1, [3]float64{1, 1, 1}, 1)
	wantKey(t, m, "watertight", true)
}

func TestModel3DWatertightFalseWithAFaceRemoved(t *testing.T) {
	open := cubeTris()[:11] // drop one triangle: four edges now belong to one face
	m := runModel3D(t, "open.stl", binarySTL(t, open, "solid open"))
	wantKey(t, m, "triangles", 11)
	wantKey(t, m, "watertight", false)
}

func TestModel3DUnsupportedExtension(t *testing.T) {
	// model3d.py:89-91 returns {"unsupported": True} for anything outside
	// _GEOMETRY_EXTS. It is a fact about the format, never an error.
	res := &Result{Meta: map[string]any{}}
	p := writeFile(t, t.TempDir(), "drawing.dwg", []byte("not really a dwg"))
	if err := extractModel3D(context.Background(), p, "dwg", Options{}, res); err != nil {
		t.Fatalf("unsupported extension must not error: %v", err)
	}
	wantKey(t, res.Meta, "unsupported", true)
	if len(res.Meta) != 1 {
		t.Fatalf("unsupported result should carry nothing else: %#v", res.Meta)
	}
}

func TestModel3DSizeGuard(t *testing.T) {
	orig := model3dMaxBytes
	t.Cleanup(func() { model3dMaxBytes = orig })
	model3dMaxBytes = 64 // lowered so the guard is testable without a 512 MiB file

	err := runModel3DErr(t, "cube.stl", binarySTL(t, cubeTris(), "solid"))
	if err == nil {
		t.Fatal("expected the size guard to fire")
	}
	if !strings.Contains(err.Error(), "guard") {
		t.Fatalf("guard failures must say so (operators triage on it): %v", err)
	}
}

func TestModel3DRejectsGarbage(t *testing.T) {
	cases := map[string][]byte{
		"cube.stl":  []byte("this is not an STL at all\n"),
		"cube.ply":  []byte("plywood\n"),
		"cube.gltf": []byte("{not json"),
		"cube.glb":  []byte("NOPE\x02\x00\x00\x00"),
		"cube.3mf":  []byte("PK-not-a-zip"),
	}
	for name, data := range cases {
		if err := runModel3DErr(t, name, data); err == nil {
			t.Fatalf("%s: expected an error for garbage input", name)
		}
	}
}

func TestModel3DHonorsCancellation(t *testing.T) {
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	p := writeFile(t, t.TempDir(), "cube.stl", binarySTL(t, cubeTris(), "solid"))
	res := &Result{Meta: map[string]any{}}
	if err := extractModel3D(ctx, p, "stl", Options{}, res); err == nil {
		t.Fatal("expected a cancelled context to abort the parse")
	}
}
